const variable_pokemons = JSON.stringify([
    {
      "#": 7,
      "Nombre": "Squirtle",
      "Descripcion": "Cuando retrae su largo cuello en el caparazón, dispara agua a una presión increíble.",
      "Imagen Principal": "imagenes/squirtle.png",
      "Imagen en pixel": "imagenes/7.png",
      "Imagen de evolucion": "imagenes/evolucion_squirtle.png",
      "Tipo 1": "AGUA",
      "Tipo 2": "",
      "Debilidad 1": "PLANTA",
      "Debilidad 2": "ELÉCTRICO",
      "Debilidad 3": "",
      "Debilidad 4": "",
      "Debilidad 5": "",
      "Altura": "0,5M",
      "Peso": "9,0kg",
      "Sexo": "Ambos",
      "Categoria": "Tortuguita",
      "Habilidad": "Torrente"
    },
    {
      "#": 35,
      "Nombre": "Clefairy",
      "Descripcion": "Se dice que la felicidad llegará a quien vea un grupo de Clefairy bailando a la luz de la luna llena",
      "Imagen Principal": "imagenes/clefairy.png",
      "Imagen en pixel": "imagenes/35.png",
      "Imagen de evolucion": "imagenes/evolucion_clefairy.png",
      "Tipo 1": "HADA",
      "Tipo 2": "",
      "Debilidad 1": "ACERO",
      "Debilidad 2": "VENENO",
      "Debilidad 3": "",
      "Debilidad 4": "",
      "Debilidad 5": "",
      "Altura": "0,6M",
      "Peso": "7,5KG",
      "Sexo": "Ambos",
      "Categoria": "Hada",
      "Habilidad": "Gran encanto Muro magico"
    },
    {
      "#": 40,
      "Nombre": "Wigglytuff",
      "Descripcion": "Cuanto más aire inhala, más aumenta de tamaño. Si se enfada, hincha el cuerpo con el fin de intimidar a su oponente.",
      "Imagen Principal": "imagenes/wigglytuff.png",
      "Imagen en pixel": "imagenes/40.png",
      "Imagen de evolucion": "imagenes/evolucion_wigglytuff.png",
      "Tipo 1": "HADA",
      "Tipo 2": "NORMAL",
      "Debilidad 1": "ACERO",
      "Debilidad 2": "VENENO",
      "Debilidad 3": "",
      "Debilidad 4": "",
      "Debilidad 5": "",
      "Altura": "1,0M",
      "Peso": "12,0KG",
      "Sexo": "Ambos",
      "Categoria": "Globo",
      "Habilidad": "Gran encanto Tenacidad"
    },
    {
      "#": 54,
      "Nombre": "Psyduck",
      "Descripcion": "Siempre padece dolores de cabeza. Tras desatar sus misteriosos poderes, la jaqueca remite unos instantes.",
      "Imagen Principal": "imagenes/psyduck.png",
      "Imagen en pixel": "imagenes/54.png",
      "Imagen de evolucion": "imagenes/evolucion_psyduck.png",
      "Tipo 1": "AGUA",
      "Tipo 2": "",
      "Debilidad 1": "PLANTA",
      "Debilidad 2": "ELÉCTRICO",
      "Debilidad 3": "",
      "Debilidad 4": "",
      "Debilidad 5": "",
      "Altura": "0,8M",
      "Peso": "19,6KG",
      "Sexo": "Ambos",
      "Categoria": "Pato",
      "Habilidad": "Humedad Humectacion"
    },
    {
      "#": 69,
      "Nombre": "Bellsprout",
      "Descripcion": "Prefiere lugares cálidos y húmedos. Atrapa pequeños Pokémon insectos con sus lianas para devorarlos.",
      "Imagen Principal": "imagenes/bellsprout.png",
      "Imagen en pixel": "imagenes/69.png",
      "Imagen de evolucion": "imagenes/evolucion_bellsprout.png",
      "Tipo 1": "PLANTA",
      "Tipo 2": "VENENO",
      "Debilidad 1": "FUEGO",
      "Debilidad 2": "PSÍQUICO",
      "Debilidad 3": "VOLADOR",
      "Debilidad 4": "HIELO",
      "Debilidad 5": "",
      "Altura": "0,7M",
      "Peso": "4,0KG",
      "Sexo": "Ambos",
      "Categoria": "Flor",
      "Habilidad": "Clorofila"
    },
    {
      "#": 129,
      "Nombre": "Magikarp",
      "Descripcion": "Es el Pokémon más débil y patético que existe, con una fuerza y velocidad prácticamente nulas.",
      "Imagen Principal": "imagenes/magikarp.png",
      "Imagen en pixel": "imagenes/129.png",
      "Imagen de evolucion": "imagenes/evolucion_magikarp.png",
      "Tipo 1": "AGUA",
      "Tipo 2": "",
      "Debilidad 1": "PLANTA",
      "Debilidad 2": "",
      "Debilidad 3": "",
      "Debilidad 4": "",
      "Debilidad 5": "",
      "Altura": "0,9M",
      "Peso": "10,0KG",
      "Sexo": "Ambos",
      "Categoria": "Pez",
      "Habilidad": "Nado rapido"
    },
    {
      "#": 132,
      "Nombre": "Ditto",
      "Descripcion": "Redistribuye las células de su cuerpo para cobrar la apariencia de lo que ve, pero vuelve a la normalidad al relajarse.",
      "Imagen Principal": "imagenes/ditto.png",
      "Imagen en pixel": "imagenes/132.png",
      "Imagen de evolucion": "imagenes/ditto.png",
      "Tipo 1": "NORMAL",
      "Tipo 2": "",
      "Debilidad 1": "LUCHA",
      "Debilidad 2": "",
      "Debilidad 3": "",
      "Debilidad 4": "",
      "Debilidad 5": "",
      "Altura": "0,3M",
      "Peso": "4,0KG",
      "Sexo": "Desconocido",
      "Categoria": "Transformacion",
      "Habilidad": "Flexibilidad"
    },
    {
      "#": 143,
      "Nombre": "Snorlax",
      "Descripcion": "No se encuentra satisfecho hasta haber ingerido 400 kg de comida cada día. Cuando acaba de comer, se queda dormido.",
      "Imagen Principal": "imagenes/snorlax.png",
      "Imagen en pixel": "imagenes/143.png",
      "Imagen de evolucion": "imagenes/evolucion_snorlax.png",
      "Tipo 1": "NORMAL",
      "Tipo 2": "",
      "Debilidad 1": "LUCHA",
      "Debilidad 2": "",
      "Debilidad 3": "",
      "Debilidad 4": "",
      "Debilidad 5": "",
      "Altura": "2,1M",
      "Peso": "460KG",
      "Sexo": "Ambos",
      "Categoria": "Dormir",
      "Habilidad": "Sebo Inmunidad"
    },
    {
      "#": 151,
      "Nombre": "Mew",
      "Descripcion": "Si se observa a través de un microscopio, puede distinguirse cuán corto, fino y delicado es el pelaje de este Pokémon.",
      "Imagen Principal": "imagenes/mew.png",
      "Imagen en pixel": "imagenes/151.png",
      "Imagen de evolucion": "imagenes/mew.png",
      "Tipo 1": "PSÍQUICO",
      "Tipo 2": "",
      "Debilidad 1": "FANTASMA",
      "Debilidad 2": "SINIESTRO",
      "Debilidad 3": "BICHO",
      "Debilidad 4": "",
      "Debilidad 5": "",
      "Altura": "0,4M",
      "Peso": "4,0KG",
      "Sexo": "Desconocido",
      "Categoria": "Nueva Especie",
      "Habilidad": "Sincronia"
    },
    {
      "#": 183,
      "Nombre": "Marill",
      "Descripcion": "La punta redonda de su cola hace las veces de flotador. En ella almacena abundantes nutrientes en forma de aceite.",
      "Imagen Principal": "imagenes/marill.png",
      "Imagen en pixel": "imagenes/183.png",
      "Imagen de evolucion": "imagenes/evolucion_marill.png",
      "Tipo 1": "AGUA",
      "Tipo 2": "HADA",
      "Debilidad 1": "PLANTA",
      "Debilidad 2": "ELÉCTRICO",
      "Debilidad 3": "VENENO",
      "Debilidad 4": "",
      "Debilidad 5": "",
      "Altura": "0,4M",
      "Peso": "8,5KG",
      "Sexo": "Ambos",
      "Categoria": "Ratón agua",
      "Habilidad": "Sebo Potencia"
    },
    {
      "#": 216,
      "Nombre": "Teddiursa",
      "Descripcion": "A Teddiursa le encanta chuparse las palmas impregnadas de dulce miel. Este Pokémon fabrica su propia miel mezclando frutos y el polen que recoge Beedrill.",
      "Imagen Principal": "imagenes/teddiursa.png",
      "Imagen en pixel": "imagenes/216.png",
      "Imagen de evolucion": "imagenes/evolucion_teddiursa.png",
      "Tipo 1": "NORMAL",
      "Tipo 2": "",
      "Debilidad 1": "LUCHA",
      "Debilidad 2": "",
      "Debilidad 3": "",
      "Debilidad 4": "",
      "Debilidad 5": "",
      "Altura": "0,6M",
      "Peso": "8,8KG",
      "Sexo": "Ambos",
      "Categoria": "Osito",
      "Habilidad": "Recogida Pies rapido"
    },
    {
      "#": 373,
      "Nombre": "Salamence",
      "Descripcion": "Un Pokémon poco común que, tras desear con todas sus fuerzas poder volar, consiguió un cuerpo alado al evolucionar.",
      "Imagen Principal": "imagenes/salamence.png",
      "Imagen en pixel": "imagenes/373.png",
      "Imagen de evolucion": "imagenes/evolucion_salamence.png",
      "Tipo 1": "DRAGON",
      "Tipo 2": "VOLADOR",
      "Debilidad 1": "HADA",
      "Debilidad 2": "DRAGON",
      "Debilidad 3": "HIELO",
      "Debilidad 4": "ROCA",
      "Debilidad 5": "",
      "Altura": "1,5M",
      "Peso": "102,6KG",
      "Sexo": "Ambos",
      "Categoria": "Dragon",
      "Habilidad": "Intimidacion"
    },
    {
      "#": 393,
      "Nombre": "Piplup",
      "Descripcion": "No le gusta que lo cuiden. Como no aprecia el apoyo de su Entrenador, le cuesta coger confianza con él.",
      "Imagen Principal": "imagenes/piplup.png",
      "Imagen en pixel": "imagenes/393.png",
      "Imagen de evolucion": "imagenes/evolucion_piplup.png",
      "Tipo 1": "AGUA",
      "Tipo 2": "",
      "Debilidad 1": "PLANTA",
      "Debilidad 2": "ELÉCTRICO",
      "Debilidad 3": "",
      "Debilidad 4": "",
      "Debilidad 5": "",
      "Altura": "0,4M",
      "Peso": "5,2KG",
      "Sexo": "Ambos",
      "Categoria": "Pingüino",
      "Habilidad": "Torrente"
    },
    {
      "#": 571,
      "Nombre": "Zoroark",
      "Descripcion": "Cuida de sus semejantes. Provoca ilusiones terroríficas para proteger tanto su guarida como a su manada de sus adversarios.",
      "Imagen Principal": "imagenes/zoroark.png",
      "Imagen en pixel": "imagenes/571.png",
      "Imagen de evolucion": "imagenes/evolucion_zoroark.png",
      "Tipo 1": "SINIESTRO",
      "Tipo 2": "",
      "Debilidad 1": "HADA",
      "Debilidad 2": "BICHO",
      "Debilidad 3": "LUCHA",
      "Debilidad 4": "",
      "Debilidad 5": "",
      "Altura": "1,6M",
      "Peso": "81,1KG",
      "Sexo": "Ambos",
      "Categoria": "Disfrazorro",
      "Habilidad": "Ilusion"
    },
    {
      "#": 635,
      "Nombre": "Hydreigon",
      "Descripcion": "Ataca y devora todo lo que se mueve. Existen numerosos relatos de pueblos enteros que fueron arrasados por este Pokémon.",
      "Imagen Principal": "imagenes/hydreigon.png",
      "Imagen en pixel": "imagenes/635.png",
      "Imagen de evolucion": "imagenes/evolucion_hydreigon.png",
      "Tipo 1": "SINIESTRO",
      "Tipo 2": "DRAGON",
      "Debilidad 1": "HADA",
      "Debilidad 2": "LUCHA",
      "Debilidad 3": "BICHO",
      "Debilidad 4": "HIELO",
      "Debilidad 5": "DRAGON",
      "Altura": "1,8M",
      "Peso": "160,0KG",
      "Sexo": "Ambos",
      "Categoria": "Voraz",
      "Habilidad": "Levitacion"
    }
  ])

const pokemons = JSON.parse(variable_pokemons)

console.log(pokemons[1].Descripcion)

let boton = -1
let squirtle = document.getElementById("squirtle")

addEventListener("click",ActualizarBoton())

function ActualizarBoton() {
    boton = 1
}

function selector_de_pokemons(){
    switch (boton) {
        case 0:
            
            break;
        case 1:

            break;
        case 2:

            break;
        default:
            break;
    }
}

